# Generated by Django 3.2.4 on 2021-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210604_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='copy_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
