# Generated by Django 3.2.4 on 2021-06-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='copy_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
