# Generated by Django 3.2.4 on 2021-06-04 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bookinstance_copy_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='copy_file',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
