# Generated by Django 3.2.4 on 2021-06-05 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210605_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='copy_file',
            field=models.FileField(blank=True, null=True, upload_to='./documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='copy_photo',
            field=models.ImageField(null=True, upload_to='./images'),
        ),
    ]
